### ISSUE TITLE
Add Hub dosen't work and using commands from command palette errors out

### ISSUE THREAD

**Issue by RomanRichter1991** [robmosca/robotinventor-vscode#6]
Errors like this:
Command 'ri5dev: Connect to a device' resulted in an error (command 'ri5devBrowser.action.pickDevice' not found)

**Comment by ghost** [comment]
Hi @RomanRichter1991,

thanks for reaching out. I am sorry the extension is not working correctly in your environment. Can you help me understand your setup, so that I can try and reproduce your problem and possibly fix it?

Until now I have tested the extension on a Mac running macOS Big Sur, with Visual Studio Code v. 1.53.2 connecting the Hub with USB and in my case it is working correctly.
Can you tell me about your setup, how you installed the extension and how to reproduce the problem?

**Comment by RomanRichter1991** [comment]
Hey! Thanks for answering so fast!
I tried:
MS/VSCode and VSCodium both on Linux and on Windows.
Installed by dropping extension folder to vs code extensions directory

**Comment by ghost** [comment]
Hi Roman,

thanks for the information!

In order to install the extension, you will need to compile and package it. You can follow the instructions reported here: https://stackoverflow.com/a/54409592/734156

Please, take into account that:

1. This is a development build, based on empirical tests I have done on the Robot Inventor set. The software is provided as-is and I cannot provide any guarantee that it works in any setup. Please, read carefully the disclaimer in the README before installing it;
2. As stated in the README, I could not test the extension on Linux or Windows, so I am not sure if it would work in those systems at all.

Hope this helps!

**Comment by RomanRichter1991** [comment]
Sadly I got same errors after compiling and packaging...
